# Generated by Django 3.0.8 on 2020-07-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaTrello', '0004_auto_20200705_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='board',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='AlphaTrello.Board'),
            preserve_default=False,
        ),
    ]
