# Generated by Django 3.0.8 on 2020-07-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaTrello', '0007_poll_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
