# Generated by Django 3.0.8 on 2020-07-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaTrello', '0009_auto_20200708_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='ahabb is awesome', max_length=255),
            preserve_default=False,
        ),
    ]
